### ISSUE TITLE
gitdiff: line 63: git file header: invalid mode line: invalid syntax

### ISSUE THREAD

**Issue by prologic** [bluekeyes/go-gitdiff#37]
Looks like your library is a bit out-of-date? Line 63 for me in sample I was testing with looks like this:

```
new file mode 100644
```

**Comment by prologic** [comment]
Which you _actually_ have tests for, so now I'm confused... 🤔

**Comment by bluekeyes** [comment]
Thanks for reporting this. Is it possible to share the full patch file that caused this error? If that's not possible, how was the patch generated (e.g. was it created by `git`, copied from an email, created by a service like GitHub of Bitbucket, etc.)?

Right now, my guess is that this is caused by something like trailing whitespace, which might have been excluded when you copied the "bad" line for this issue.

**Comment by prologic** [comment]
So... I created the patch with `git format-patch` and send it to myself with `git send-email`. I then downloaded the entire contents of the Email (using the Rainloop Web interface) as an `.eml` file which appears to have full email headers. I piped that to a cli tool I write using your library and ran into that error and it has since befuddled me 😅 -- I suspect you're right.

**Comment by prologic** [comment]
@bluekeyes Ahh awesome! I never got as far as this in debugging this! Nice one 👌 (btw, where can I discuss some other ideas with you? I have a need that I _think_ your library could help fulfll...)

**Comment by bluekeyes** [comment]
@prologic I think creating a new issue is the best way to discuss ideas or usage of this library
